services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app
    environment:
      - DATABASE_URL=sqlite:///./sqlite.db
    command: poetry run uvicorn main:app --proxy-headers --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
    networks:
      - fastapi_network

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    networks:
      - fastapi_network
    depends_on:
      - app

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - fastapi_network

networks:
  fastapi_network:
    driver: bridge