services:
  traefik:
    image: traefik:v2.9
    container_name: traefik_spytime
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=andreylagunovich@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./letsencrypt:/letsencrypt"
    restart: unless-stopped
    depends_on:
      pg:
        condition: service_healthy

  app:
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: app_spytime
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`api.spytime.online`)"
      - "traefik.http.routers.app.entrypoints=web"
      - "traefik.http.routers.app.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.app-secure.rule=Host(`api.spytime.online`)"
      - "traefik.http.routers.app-secure.entrypoints=websecure"
      - "traefik.http.routers.app-secure.tls.certresolver=letsencrypt"
      - "traefik.http.services.app.loadbalancer.server.port=8000"
    environment:
      APP_CONFIG__DB__URL: postgresql+asyncpg://user:user@pg:5432/app
    depends_on:
      pg:
        condition: service_healthy
    restart: unless-stopped

  pg:
    image: postgres:16.4-alpine
    container_name: postgres_spytime
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d app" ]
      interval: 5s
      timeout: 3s
      retries: 3
    restart: unless-stopped

volumes:
  pgdata: