services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app
    environment:
      - DATABASE_URL=sqlite:///./sqlite.db
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped