"""Add lobbies table

Revision ID: 635d76c8bf47
Revises: 
Create Date: 2025-01-30 15:08:43.119161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '635d76c8bf47'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lobbies',
    sa.Column('lobby_id', sa.UUID(), nullable=False),
    sa.Column('players', sa.JSON(), nullable=False),
    sa.Column('location', sa.JSON(), nullable=False),
    sa.Column('spies_team', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('lobby_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lobbies')
    # ### end Alembic commands ###
