"""Create table lobbies

Revision ID: d8a2654d2ed3
Revises:
Create Date: 2025-03-23 01:19:13.141456

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d8a2654d2ed3"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lobbies",
        sa.Column("lobby_id", sa.UUID(), nullable=False),
        sa.Column("players", sa.JSON(), nullable=False),
        sa.Column("location", sa.JSON(), nullable=False),
        sa.Column("spies_team", sa.Boolean(), nullable=False),
        sa.Column("lang", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("lobby_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("lobbies")
    # ### end Alembic commands ###
