"""new

Revision ID: 7abe3756c402
Revises:
Create Date: 2025-08-14 02:15:45.955080

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7abe3756c402"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lobbies",
        sa.Column("lobby_id", sa.UUID(), nullable=False),
        sa.Column("players", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("location", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("spies_team", sa.Boolean(), nullable=False),
        sa.Column("lang", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("lobby_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("lobbies")
    # ### end Alembic commands ###
