"""Add lobbies table

Revision ID: 44e5d2ed80fb
Revises: 
Create Date: 2025-01-29 18:55:13.545238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44e5d2ed80fb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lobbies',
    sa.Column('lobby_id', sa.UUID(), nullable=False),
    sa.Column('players', sa.JSON(), nullable=False),
    sa.Column('location', sa.JSON(), nullable=False),
    sa.Column('spies_team', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('lobby_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lobbies')
    # ### end Alembic commands ###
