"""create tables lobbies

Revision ID: c5ff8fb15b96
Revises: 
Create Date: 2025-01-22 13:19:22.477830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5ff8fb15b96'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lobbies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('players', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lobbies_id'), 'lobbies', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lobbies_id'), table_name='lobbies')
    op.drop_table('lobbies')
    # ### end Alembic commands ###
